Refresh model
beto-devnet/Ed-Fi-DataImport pull request #1
Opened 2024-04-26 14:59 UTC by beto-devnet

2024-04-26 22:13 UTC, nsd-sergio commented
Hi @beto-devnet

2024-04-26 22:18 UTC, nsd-sergio requested changes
Could you please review this changes

thanks

2024-04-26 22:18 UTC, nsd-sergio commented on DataImport.Web/appsettings.json
> +    },
@beto-devnet  remove empty spaces.

2024-04-26 22:18 UTC, nsd-sergio commented on DataImport.Web/Features/ApiServers/AddEditApiServer.cshtml
> +                        console.log("error");
@beto-devnet remove console.log

2024-04-26 22:18 UTC, nsd-sergio commented on DataImport.Web/Features/ApiServers/RefreshDataModel.cs
> +                var metadataFromRresources = await _database
fix spelling

2024-04-26 22:18 UTC, nsd-sergio commented on DataImport.Web/Features/ApiServers/RefreshDataModel.cs
> +
remove empty space

2024-04-26 22:18 UTC, nsd-sergio commented on DataImport.Web.Tests/Features/ApiServers/RefreshDataModelTests.cs
> +        public void ShouldThrowAnExceptionWhenApiServerNotExist(int ApiServerId)
should be apiServerId

2024-04-26 22:18 UTC, nsd-sergio commented on DataImport.Web.Tests/Features/ApiServers/RefreshDataModelTests.cs
> +        [TestCase(0)]
why TestCase[0] and not just Test?

2024-04-29 15:59 UTC, beto-devnet commented on DataImport.Web/appsettings.json
> +    },
done

2024-04-29 15:59 UTC, beto-devnet commented on DataImport.Web/Features/ApiServers/RefreshDataModel.cs
> +                var metadataFromRresources = await _database
done

2024-04-29 15:59 UTC, beto-devnet commented on DataImport.Web.Tests/Features/ApiServers/RefreshDataModelTests.cs
> +        public void ShouldThrowAnExceptionWhenApiServerNotExist(int ApiServerId)
done

2024-04-29 15:59 UTC, beto-devnet commented on DataImport.Web.Tests/Features/ApiServers/RefreshDataModelTests.cs
> +        [TestCase(0)]
done

2024-04-29 18:45 UTC, closed without merging